apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  system: "system:default/lab"
  type:  "service"
  lifecycle: "experimental"
  owner: "group:default/devxp-tech"
metadata:
  name: "demo-app"
  description: "demo-app"
  annotations:
    github.com/project-slug: devxp-tech/demo-app
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: demo-app-dev
    backstage.io/kubernetes-id: "demo-app"
    sonarqube.org/project-key: "demo-app"
    grafana/tag-selector: "Kubernetes"
    prometheus.io/rule: container_cpu_usage_seconds_total{namespace="demo-app"}
    prometheus.io/alert: all
  tags:
    - golang
    # - system:default/lab
    - "service"
    - "experimental"
  links:
    - url: https://demo-app.devxp-tech.io
      title: Website
      icon: Website
    - url: https://grafana.devxp-tech.io/
      title: Dashboard
      icon: dashboard
    - url: https://alerts.devxp-tech.io/
      title: Alerts
      icon: alert
    - url: https://argocd.devxp-tech.io/applications/demo-app-dev?resource=
      title: ArgoCD
      icon: cloud
    - url: https://grafana.devxp-tech.io/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=Prometheus&var-namespace=demo-app&var-resolution=30s
      title: Logs
      icon: cloud
    - url: https://kiali.devxp-tech.io/kiali/console/graph/namespaces/?traffic=grpc%2CgrpcRequest%2Chttp%2ChttpRequest%2Ctcp%2CtcpSent&graphType=versionedApp&namespaces=demo-app&duration=120&refresh=60000&idleNodes=true&layout=kiali-breadthfirst&namespaceLayout=kiali-dagre
      title: Kiali
      icon: cloud
